
name_dict = {'Grishma':[6, 'Highland Park'], 
             'Nayara':[9, 'Highland Park'],
             'Manu':[6, 'Highland Park'],
             'Anmol':[9, 'Highland Park'],
             'Preshika':[13, 'Edison'],
             'Sanchita':[13, 'Edison'],
             'Robin':[6, 'East Brunswick'],
             'Myra':[6, 'South Brunswick'],
             'Preetisha':[9, 'Piscataway'], 
             'Ishara':[13, 'Piscataway'],
             'Sudu':[6, 'East Windsor'], 
             'Dena':[13, 'East Windsor'], 
             'Arvi':[3, 'East Windsor'], 
}